#

diff --git a/.github/workflows/keypractica.yaml b/.github/workflows/keypractica.yaml
--- a/.github/workflows/keypractica.yaml
+++ b/.github/workflows/keypractica.yaml
@@ -20,9 +20,7 @@ jobs:
           distribution: 'temurin'
 
       - name: Build Project with Maven
-        run: |
-          echo "Running Maven package command"
-          mvn package -Dquarkus.package.type=uber-jar -DskipTests
+        run: mvn package -Dquarkus.package.type=uber-jar -DskipTests
         env:
           MAVEN_CLI_OPTS: '-s /path/to/settings.xml -B'
 
@@ -34,6 +32,7 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           port: ${{ secrets.SERVER_PORT }}
           script: |
+            set -e  # Exit immediately if a command exits with a non-zero status.
             echo "Starting deployment to server at ${host}"
             echo "Transfer the JAR file to the server"
             scp ${{ github.workspace }}/target/quarkus-keypractica-runner.jar ${username}@${host}:/home/keypractica/be_server/projects/target
@@ -42,12 +41,10 @@ jobs:
             echo "Starting the Keypractica service"
             sudo systemctl start keypractica
             echo "Deployment completed successfully"
-        env:
-          DEBUG: true
-
       - name: Send Message to Telegram
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_CHAT_ID }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
           message: "Hi! The Keypractica backend has been updated"
+
